version: '3.8'

services:
  # Service MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Service phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network

  # Service PHP/Laravel (mon-projet-app)
  app:
    image: ferdaoussbo/mon-projet-app:latest
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - app-network

  # Service Nginx
  webserver:
    image: nginx:alpine
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  # Service Node/Angular (mon-projet-node)
  node:
    image: ferdaoussbo/mon-projet-node:latest
    container_name: angular_app
    volumes:
      - ./angular:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "4200:4200"
    networks:
      - app-network
    restart: unless-stopped
    command: >
      sh -c "npm install && 
      ng serve --host 0.0.0.0 --port 4200 --disable-host-check"

# Volumes et réseaux
volumes:
  dbdata:
    driver: local

networks:
  app-network:
    driver: bridge

