name: Build & Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le repo
        uses: actions/checkout@v3

      - name: Se connecter à DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et push image Laravel
        run: |
          docker build -t ferdaoussbo/mon-projet-app ./laravel
          docker push ferdaoussbo/mon-projet-app

      - name: Build et push image Angular
        run: |
          docker build -t ferdaoussbo/mon-projet-node ./angular
          docker push ferdaoussbo/mon-projet-node
